### ISSUE TITLE
make setup broken - asks for python-serial

### ISSUE THREAD

**Issue by elomage** [edi-riga/MansOS#1]
Initial setup after downloading MansOS on Ubuntu 20.04.
Go to demo/Blink/
make telosb setup 
...crash

**Comment by jjanis** [comment]
Ubnutu 20.04 does not include Python2.x anymore and pyhton-serial is not in the default repositories, but most of MansOS is based on Python2.7.

The correct fix would be to migrate MansOS to Python3.

Meanwhile I have found that on Ubuntu 20.04 you need to:
- Remove the python-serial from line 477 of mos/make/Makefile as #2 suggested
- Install python manually with **apt install python**, this allows to compile, not sure if upload works
- To use tools/serial/ser.py install python3-serial and run the script with python3, it _should_ work

**Comment by elomage** [comment]
Fixed in 9d48c1ec0fd7ebbec493cfc7c4165f5852b7ceb8
